name: CI-CD Lambda Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::058264356572:role/sts-tenant-lambda-role
          aws-region: ap-south-1

      - name: Install dependencies
        run: npm ci

      - name: Package Lambda function
        run: |
          mkdir -p dist
          rsync -av --exclude='node_modules' --exclude='.git' ./ dist
          cd dist
          zip -r ../publish.zip .
          cd ..

      - name: Deploy to AWS Lambda
        run: |
          aws lambda update-function-code --function-name lambda-github-actions --zip-file fileb://publish.zip --region ap-south-1
