name: CI-CD Lambda Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  # Adjust node version as needed

      - name: Install dependencies
        run: npm ci

      - name: Build Lambda function
        run: npm run build  # Adjust this script as per your package.json

      - name: Package Lambda function
        run: |
          mkdir -p dist
          cp -r !(node_modules) dist/
          cd dist
          zip -r ../publish.zip .
          cd ..

      - name: Deploy to AWS Lambda
        run: |
          aws lambda update-function-code --function-name lambda-github-actions --zip-file fileb://publish.zip --region ap-south-1
